// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitConversionApi.Infrastructure.Data;

#nullable disable

namespace UnitConversionApi.Infrastructure.Migrations
{
    [DbContext(typeof(UnitConversionDbContext))]
    partial class UnitConversionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnitConversionApi.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Factor")
                        .HasColumnType("float");

                    b.Property<bool>("MainReference")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitCategoryId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Factor = 1.0,
                            MainReference = true,
                            Name = "meter",
                            UnitCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Factor = 1000.0,
                            MainReference = false,
                            Name = "kilometer",
                            UnitCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Factor = 1609.3399999999999,
                            MainReference = false,
                            Name = "mile",
                            UnitCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Factor = 1.0,
                            MainReference = true,
                            Name = "kilogram",
                            UnitCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            Factor = 0.001,
                            MainReference = false,
                            Name = "gram",
                            UnitCategoryId = 2
                        },
                        new
                        {
                            Id = 6,
                            Factor = 1.0,
                            MainReference = true,
                            Name = "celsius",
                            UnitCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            Factor = 0.0,
                            MainReference = false,
                            Name = "fahrenheit",
                            UnitCategoryId = 3
                        });
                });

            modelBuilder.Entity("UnitConversionApi.Domain.Entities.UnitCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Length"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weight"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Temperature"
                        });
                });

            modelBuilder.Entity("UnitConversionApi.Domain.Entities.Unit", b =>
                {
                    b.HasOne("UnitConversionApi.Domain.Entities.UnitCategory", "UnitCategory")
                        .WithMany("Units")
                        .HasForeignKey("UnitCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitCategory");
                });

            modelBuilder.Entity("UnitConversionApi.Domain.Entities.UnitCategory", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
